# once a new release tag is created, circle.yml sends a request to travis.yml
# travis.yml builds the documentation in this repo and creates a pull request
language: node_js
notifications:
  email: false
    
cache:
  directories:
    - node_modules
    - /home/travis/.rvm/ # https://docs.travis-ci.com/user/caching/#cache-rvm-ruby-version-for-non-ruby-projects
    - $HOME/Library/Caches/Homebrew # caches brew directory
git:
  depth: 3
node_js:
  - 12
install:
  # prevents travis from running package.json > scripts > install
  - npm install --ignore-scripts
  # links the package to access docs-release-pull-request cli
  - npm link @mapbox/docs-release-helpers
env:
  # Do not automatically update before running `brew install`, `brew upgrade` or `brew tap`.
  HOMEBREW_NO_AUTO_UPDATE: 1
  # Do not run `brew cleanup`
  HOMEBREW_NO_INSTALL_CLEANUP: 1
jobs:
  include:
    - name: "Build Maps Release Docs"
      os: osx
      osx_image: xcode10.2
      # only run this job if conditions are met (circleci will trigger it)
      if: env(SDK_FLAVOR) = maps AND env(RELEASE_TAG) IS PRESENT
      script:
        - git config user.email "MapboxCI@users.noreply.github.com"
        # generate the documentation given the release tag and commit it and then
        # from the commit created in the shell script, push a new branch, and create a pull request in this repo
        - ./scripts/docs-update-maps.sh $RELEASE_TAG && docs-release-pull-request -s $SDK_FLAVOR -t $RELEASE_TAG -b publisher-staging -p ios -r mapbox-gl-native-ios
        # use `docs-release-pull-request --help` to see all options
